### PR TITLE
github: Add SECURITY.md for how to report security issues

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
A repo setting needs to be enabled for private security issues to be functional, please see https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by tomponline** [comment]
done

**Comment by simondeziel** [comment]
@tomponline I see you've enabled the feature but apparently accidentally closed the PR to add the security policy ;)

**Comment by tomponline** [comment]
Ah missed that bit, ill leave that for @roosterfish or @masnax

**Review by roosterfish — APPROVED** [review]
Thanks!

**Pull request merged**
