### PR TITLE
Update microcluster & microceph dependencies 

### PR DESCRIPTION
**Pull request by masnax**

### CODE REVIEW

**Review by roosterfish — DISMISSED** [review]
LGTM!

There are some commits that include changes from other packages too but I guess as long as we don't need to backport stuff we can ignore this for now.

**Comment by masnax** [comment]
@gabrielmougard Got any idea what's going on with the add test? I find it odd that it's failing now since it seems unrelated to this PR. 

Looks like the cluster network isn't being set on the OSD config. Weird thing is I can't seem to reproduce the issue locally on my end.

https://github.com/canonical/microcloud/actions/runs/9492146264/job/26160759670?pr=320#step:13:1548

**Comment by gabrielmougard** [comment]
That's weird indeed. Taking a look

**Comment by masnax** [comment]
@roosterfish Alright, tests are passing again so it needs another approval, thanks :)

**Comment by roosterfish** [comment]
> @roosterfish Alright, tests are passing again so it needs another approval, thanks :)

Good news! Was it just another race in the test suite?

**Review by roosterfish — APPROVED** [review]

**Pull request merged**
