### PR TITLE
all: Move `microcloud/*` one level up 

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Review by roosterfish — APPROVED** [review]
LGTM

**Comment by masnax** [comment]
Oops sorry, needs a rebase now.

**Comment by simondeziel** [comment]
I think now would be a good time to make all the checks required as they are sufficiently reliable. The one exception might be the slow and big one `interactive` which might remain optional.

**Comment by simondeziel** [comment]
> I think now would be a good time to make all the checks required as they are sufficiently reliable. The one exception might be the slow and big one `interactive` which might remain optional.

As luck would have it, the `interactive` check failed ;)

**Comment by simondeziel** [comment]
@masnax please merge it while it's green ;)
Thank you!

**Review by masnax — APPROVED** [review]

**Pull request merged**
