### PR TITLE
doc: Add new MicroCloud logos in the reference page

### PR DESCRIPTION
**Pull request by gabrielmougard**
JIRA ticket: https://warthogs.atlassian.net/browse/LXD-2123

### CODE REVIEW

**Review by minaelee — DISMISSED** [review]

**Comment by roosterfish** [comment]
When viewing the docs, should we rather get rid of the logo here entirely? See 

Screenshot from 2024-11-06 12-22-37

**Comment by minaelee** [comment]
> When viewing the docs, should we rather get rid of the logo here entirely? See
> 
> Screenshot from 2024-11-06 12-22-37

I agree.

**Comment by gabrielmougard** [comment]
yes I agree too

**Comment by gabrielmougard** [comment]
@roosterfish @minaelee updated. Could we keep the logos in the `images/` directory though? I have an other PR that will use them.

**Comment by roosterfish** [comment]
@gabrielmougard are the images required in this PR? I think they should rather be added in https://github.com/canonical/microcloud/pull/461.

**Review by roosterfish — APPROVED** [review]

**Pull request merged**
