### PR TITLE
Fix lookup subnet

### LINKED ISSUE #331: Preseed `lookup_subnet` does not work as intended and will only work with host IP
### Summary
`lookup_subnet` has to be the IP address of the host node and not the subnet. This is actually how it is tested in [preseed.sh](https://github.com/canonical/microcloud/blob/5992c468850bea3f4507d5b7e34feb70b9760dba/test/suites/preseed.sh#L92). In this preseed test it would be better to use `lxc network get <network> ipv4.address`  instead. 

It also appears that the interactive method is affected and is using the host IP instead of a subnet to search for other machines and or is phrased incorrectly.

### Preseed
`lookup_subnet` defined in a preseed.
```
lookup_subnet: 10.32.16.1/24
```
This is the error associated.
```
cat seed | microcloud init --preseed
Error: Failed to bootstrap local MicroCloud: Failed to listen on https socket: listen tcp 10.32.16.1:9443: bind: cannot assign requested address
```

### Interactive
In the interactive initialization it mentions the use of the host IP address and the phrasing seems to imply limiting the search to the displayed subnet found.
```
microcloud init
Waiting for LXD to start...
Using address "10.32.16.135" for MicroCloud
Limit search for other MicroCloud servers to 10.32.16.135/24? (yes/no) [default=yes]:  
```

### PR DESCRIPTION
**Pull request by MggMuggins**
Presently, `lookup_subnet` in the [MicroCloud preseed](https://canonical-microcloud.readthedocs-hosted.com/en/latest/how-to/initialise/#non-interactive-configuration) is used to determine the listen address of the services running on the local member. 

Instead, this PR uses the first address assigned to `lookup_interface` that falls within the `lookup_subnet` to determine the listen address for the local services. 

Fixes #331

### CODE REVIEW

**Review by roosterfish — COMMENTED** [review]
The change in general looks good.

But I am wondering if we actually require the `lookup_interface` config setting.
Let's say you set `lookup_subnet: 10.0.1.1/24`. Now what is the benefit of also setting `lookup_interface`? Wouldn't this be an invalid configuration on the host itself (in regards to routing) if the same network is configured on multiple interfaces?

**Comment by masnax** [comment]
> The change in general looks good.
> 
> But I am wondering if we actually require the `lookup_interface` config setting. Let's say you set `lookup_subnet: 10.0.1.1/24`. Now what is the benefit of also setting `lookup_interface`? Wouldn't this be an invalid configuration on the host itself (in regards to routing) if the same network is configured on multiple interfaces?

I don't think there's anything wrong with having two interfaces where the subnet of one fits within the subnet of another. Since the subnet passed to `lookup_subnet` does not have to match precisely with the subnet on the interface, it can be ambiguous which interface ends up getting used. If we require specifying the interface then there is no ambiguity.

**Comment by masnax** [comment]
Looking at the mDNS logic a little closer, I see this:
* All systems broadcast their information over every capable interface and subnet.
* `lookup_subnet` is used for lookup on the init node. It will find all records from every subnet of all potential joiners.
* From the results of that lookup, we filter the output based on whether it fits in `lookup_subnet` manually.

So the issue is that the `lookup_subnet` doesn't actually have anything to do with the `lookup_interface`. So we will still need two keys.

**Comment by masnax** [comment]
Here's the issue that the introduction of `lookup_interface` was trying to solve. So it looks like setups with interfaces that have conflicting subnets is a real use case: https://github.com/canonical/microcloud/issues/148

**Comment by masnax** [comment]
I don't think any of the points here are blocking for this PR, so I'm going to file an issue for investigating the need for `lookup_interface` and merge this one.

**Review by masnax — APPROVED** [review]

**Pull request merged**
