### PR TITLE
microcloud/version: Bump version to 1.1

### PR DESCRIPTION
**Pull request by masnax**

### CODE REVIEW

**Comment by tomponline** [comment]
Where is the api version specified?

**Comment by tomponline** [comment]
Please can you change commit message to:

```
Release MicroCloud 1.1"
```

**Comment by masnax** [comment]
> Where is the api version specified?

MicroCloud doesn't have much of an API, and what little there's is isn't user-accessible, so there's no explicit versioning yet. There's schema versioning built into microcluster but microcloud doesn't extend it yet.

**Comment by tomponline** [comment]
> > Where is the api version specified?
> 
> MicroCloud doesn't have much of an API, and what little there is isn't user-accessible, so there's no explicit versioning yet. There's schema versioning built into microcluster but microcloud doesn't extend it yet.

Hrm are you saying the endpoints don't start with /1.0?

**Comment by masnax** [comment]
> > > Where is the api version specified?
> > 
> > 
> > MicroCloud doesn't have much of an API, and what little there is isn't user-accessible, so there's no explicit versioning yet. There's schema versioning built into microcluster but microcloud doesn't extend it yet.
> 
> Hrm are you saying the endpoints don't start with /1.0?

Sorry, I misunderstood you a bit. I thought you meant a record of API updates like we have with LXD. 

The actual API version is defined by MicroCluster here, it's not managed by MicroCloud:
`https://github.com/canonical/microcluster/blob/e3b7b60a4d71577f5d0f5460f71dbb33dfcb5d9c/internal/rest/client/client.go#L35`

**Pull request merged**
